from tkinter import *
sayfa= Tk()
ustFrame=Frame(sayfa)
ustFrame.pack()
altFrame=Frame(sayfa)
altFrame.pack(side=RIGHT)
buton1= Button(ustFrame, text="Buton 1", fg="red")
buton2= Button(ustFrame, text="Buton 2", fg="blue")
buton3= Button(ustFrame, text="Buton 3", fg="green")
buton4= Button(altFrame, text="Buton 4", fg="purple")
buton1.pack(side=LEFT)
buton2.pack(side=LEFT)
buton3.pack(side=LEFT)
buton4.pack(side=BOTTOM)
sayfa.mainloop()