from tkinter import *
sayfa=Tk()
sayfa.title("Benim Sayfam")
sayfa.geometry("300x300")
bir=Label(sayfa,text="Bir",bg="red",fg="white")
bir.pack()
iki=Label(sayfa,text="İki",bg="green",fg="black")
iki.pack(fill=X)
uc=Label(sayfa,text="Üç",bg="Blue",fg="white")
uc.pack(side=LEFT,fill=Y)
dört=Label(sayfa,text="Dört",bg="yellow",fg="black")
dört.pack(fill=X)
beş=Label(sayfa,text="Beş",bg="pink",fg="white")
beş.pack(side=LEFT,fill=Y)
alti=Label(sayfa,text="Alti",bg="cyan",fg="white")
alti.pack(fill=X)
yedi=Label(sayfa,text="Yedi",bg="brown",fg="white")
yedi.pack(side=LEFT,fill=Y)
sayfa.mainloop()
